language: 
  - python
  - node_js
  - go
  - java
go:
  - tip
python:
  - "2.7"
node_js:
  - "0.11"
jdk:
  - oraclejdk7
before_script:
  - "pip install -r requirements.txt"
  - "echo $JAVA_HOME"
  - "wget http://services.gradle.org/distributions/gradle-1.11-bin.zip"
  - "unzip gradle-1.11-bin.zip"
  - "export GRADLE_HOME=$PWD/gradle-1.11"
  - "export PATH=$GRADLE_HOME/bin:$PATH"
script: make
