language: 
  - python
  - node_js
  - go
  - java
go:
  - tip
python:
  - "2.7"
node_js:
  - "0.11"
jdk:
  - openjdk7
  - oraclejdk7
before_script:
  - "pip install -r requirements.txt"
  - "sudo apt-get install gradle"
script: make
